### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by joferrao** [pecigonzalo/pre-commit-terraform-vars#4]
First of all, thank you for making the current repository available to the Open Source community. The project has been for sometime without activity, but on the off change that you are still maintaining it, would you please consider adding a LICENSE file to the project?

**Comment by joferrao** [comment]
@pecigonzalo just hoping you get some time review this request. I would also be happy to open a PR with the type of license you'd require (in the case that you do decide to add it)

**Comment by pecigonzalo** [comment]
I'm sorry for the delay here. I'll a license today.

**Comment by pecigonzalo** [comment]
Done, its now licensed under Apache 2.0. Im really sorry for the delay and lack of activity here. This was working as is, so not much more to add, but if you would like to see any features or face any bugs, do let me know.

**Comment by joferrao** [comment]
> Done, its now licensed under Apache 2.0. Im really sorry for the delay and lack of activity here. This was working as is, so not much more to add, but if you would like to see any features or face any bugs, do let me know.

No reason to be sorry, I really appreciate your feedback and action!
