### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by istrazimiri-deloitte** [pecigonzalo/pre-commit-terraform-vars#5]
Hi, thanks for creating this OpenSource repository it is really helpful. I just wanted to kindly ask, if it is possible to create a release version so we can reference it ? Thank you and best regards.

**Comment by pecigonzalo** [comment]
Sure thing, Ill work on it over the weekend!

**Comment by istrazimiri-deloitte** [comment]
Hi @pecigonzalo, can you please make sure this is done whenever you can ? 
Thank you and have a great weekend :)

**Comment by pecigonzalo** [comment]
Done https://github.com/pecigonzalo/pre-commit-terraform-vars/releases/tag/v1.0.0

**Comment by istrazimiri-deloitte** [comment]
Thank you
